export const  selectedModule = ["Introduction to Business Sustainability",
    "Sustainability Plan Development",
    "Sustainability Plan Implementation",
    "Decarbonisation: Achieving Net Zero",
    "Circular Economy",
    "Business with Biodiversity",
    "Diversity, Equity, and Inclusion",
    "Sustainable Finance",
    "Sustainable Operations",
    "Sustainable Supply Chain",
    "Green Marketing",
    "ESG Reporting and Auditing",
    "Corporate Sustainability Reporting Directive"];

export const moduleCourseIdMap = {
    "Introduction to Business Sustainability": "2755212",
    "Sustainability Plan Development": "2755219",
    "Sustainability Plan Implementation": "2755224",
    "Decarbonisation: Achieving Net Zero": "2755233",
    "Circular Economy": "2755243",
    "Business with Biodiversity": "2755260",
    "Diversity, Equity, and Inclusion": "2755264",
    "Sustainable Finance": "2755272",
    "Sustainable Operations": "2755276",
    "Sustainable Supply Chain": "2755278",
    "Green Marketing": "2755281",
    "ESG Reporting and Auditing": "2755283",
    "Corporate Sustainability Reporting Directive": "2730358",
}